//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enhanced.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enhanced.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen class name.
        /// </summary>
        internal static string DoxygenClassNameDisplayName {
            get {
                return ResourceManager.GetString("DoxygenClassNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen command.
        /// </summary>
        internal static string DoxygenCommandDisplayName {
            get {
                return ResourceManager.GetString("DoxygenCommandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen \dir path.
        /// </summary>
        internal static string DoxygenDirPathDisplayName {
            get {
                return ResourceManager.GetString("DoxygenDirPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen emphasized word.
        /// </summary>
        internal static string DoxygenEmphasizeDisplayName {
            get {
                return ResourceManager.GetString("DoxygenEmphasizeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen group name.
        /// </summary>
        internal static string DoxygenGroupNameDisplayName {
            get {
                return ResourceManager.GetString("DoxygenGroupNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen group title.
        /// </summary>
        internal static string DoxygenGroupTitleDisplayName {
            get {
                return ResourceManager.GetString("DoxygenGroupTitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen header file name.
        /// </summary>
        internal static string DoxygenHeaderFileDisplayName {
            get {
                return ResourceManager.GetString("DoxygenHeaderFileDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen header name.
        /// </summary>
        internal static string DoxygenHeaderNameDisplayName {
            get {
                return ResourceManager.GetString("DoxygenHeaderNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen #define macro name.
        /// </summary>
        internal static string DoxygenMacroNameDisplayName {
            get {
                return ResourceManager.GetString("DoxygenMacroNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen function parameter name.
        /// </summary>
        internal static string DoxygenParamArgNameDisplayName {
            get {
                return ResourceManager.GetString("DoxygenParamArgNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxygen function parameter direction.
        /// </summary>
        internal static string DoxygenParamDirectionDisplayName {
            get {
                return ResourceManager.GetString("DoxygenParamDirectionDisplayName", resourceCulture);
            }
        }
    }
}
